version: '3.8'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped